version: '3'

services:

# CONTAINER DO BANCO DE DADOS
  shortener_pgsql:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: 'shortener_pgsql'
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword

# CONTAINER DO SISTEMA GERENCIADOR DE BANCO DE DADOS (SGBD)
  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  pg-data:
